# 存储每日数据，临时数据
data:
  redis:
    ip: 192.168.8.23
    port: 8379
    db: 0
# 消息队列,存储持久数据
queue:
  redis:
    ip: 192.168.8.23
    port: 8379
    db: 1
# 静态文件
static:
  path: ./static
# 日志目录
log:
  path: /Users/lei/workspace/gitlab/vmatch-stats/test_logs
# ip库文件路径
ipFile: /Users/lei/go/src/vmStat/ip2region.db
# 日志级别
logLevel: debug



